

num_epoch = 10;
accuracies = zeros(1, num_epoch);

for i = 1:num_epoch
    [train_image_paths, ...
                            test_image_paths, ...
                            train_labels, ...
                            test_labels, ...
                            categories, ...
                            abbr_categories, ...
                            predicted_categories] = epoch(i);

    num_categories = length(categories);
    [accuracy, confusion_matrix] = create_confusion_matrix(predicted_categories, test_labels, categories, num_categories);
    fprintf('Current Accuracy at epoch %i = %.3f\n', i, accuracy)
    accuracies(i) = accuracy;
end

% Fixed 100 images per category set
% 0.796

% Random 50 images per categories:
% 0.7760    0.7720    0.8013    0.7813    0.7747    0.7813    0.7947    0.7773    0.7813    0.7920
create_results_webpage( train_image_paths, ...
                        test_image_paths, ...
                        train_labels, ...
                        test_labels, ...
                        categories, ...
                        abbr_categories, ...
                        predicted_categories)