

num_epoch = 5;
accuracies = zeros(1, num_epoch);

for i = 1:num_epoch
    [train_image_paths, ...
                            test_image_paths, ...
                            train_labels, ...
                            test_labels, ...
                            categories, ...
                            abbr_categories, ...
                            predicted_categories] = epoch();

    num_categories = length(categories);
    [accuracy, confusion_matrix] = create_confusion_matrix(predicted_categories, test_labels, categories, num_categories);
    fprintf('Current Accuracy at epoch %i = %.3f\n', i, accuracy)
    accuracies(i) = accuracy;
end

% 0.7467    0.7400    0.7560    0.7413    0.7213
create_results_webpage( train_image_paths, ...
                        test_image_paths, ...
                        train_labels, ...
                        test_labels, ...
                        categories, ...
                        abbr_categories, ...
                        predicted_categories)